/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 1.2 */
/* Tue Feb 20 12:31:07 2024 */

/* parameterized module instance */
i2c_s __ (.i2c0acko( ), .i2c0adri( ), .i2c0clki( ), .i2c0csi( ), 
    .i2c0dati( ), .i2c0dato( ), .i2c0i2cirq( ), .i2c0i2cwkup( ), 
    .i2c0pmuwkup( ), .i2c0scl( ), .i2c0sda( ), .i2c0stbi( ), .i2c0wei( ));
